Develop
KilopaNye/taipei-day-trip pull request #8
Opened 2023-10-04 13:42 UTC by KilopaNye

彭彭老師您好。我是吳伯韋，目前已將作業基本作業要求製作完成，再請您根據以下網址進行測試，謝謝老師。
http://3.114.143.152:3000

2023-10-04 17:20 UTC, cwpeng requested changes
Your order number in the thankyou page does not align with order number in query string.

2023-10-05 02:37 UTC, KilopaNye commented
已修正訂單編號不一致的問題，再請您重新審閱。謝謝老師!
http://3.114.143.152:3000

2023-10-05 07:32 UTC, cwpeng approved these changes
OK. Done.

2023-10-05 07:32 UTC, KilopaNye commented
謝謝老師!

2023-10-05 07:32 UTC, merged